spring.application.name=jwtValidator
logging.level.com.kocmetehan.jwtValidator=INFO
server.port=80

# When the message field in response in Null, it won't be shown to user with this configuration
spring.jackson.default-property-inclusion=non_null


ratelimit.request.per.minute=20